### ISSUE TITLE
Running in background

### ISSUE THREAD

**Issue by mmativ** [kinglozzer/silverstripe-tinypng#11]
Hi, it is possible to compress the image via calling methods or running in background so we dont need to visit each page?

**Comment by lozcalver** [comment]
I’m afraid not without building a custom CLI task. I’ve done that in the past with a list of known images/image sizes, then just calling for example `$image->Fill(123, 456)->getURL()` should be enough to trigger the actual resample.

You could also try running something like `Director::test($this->Link())` in `onAfterPublish` to trigger a fake page view each time the page is published
