### ISSUE TITLE
Getting a fatal error while building.

### ISSUE THREAD

**Issue by martinviolet88** [kinglozzer/silverstripe-tinypng#13]
Fatal error: Class Kinglozzer\SilverStripeTinyPng\CompressedEncoder contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Intervention\Image\AbstractEncoder::processHeic) in ....vendor/kinglozzer/silverstripe-tinypng/src/CompressedEncoder.php on line 18

**Comment by lozcalver** [comment]
Thanks, it seems `intervention/image` doesn’t follow semantic versioning so keep pushing breaking changes 😞. I’ve fixed it and tagged as 3.0.2

**Comment by martinviolet88** [comment]
Thanks!
