### ISSUE TITLE
Compressed being called unexpectedly

### ISSUE THREAD

**Issue by nfauchelle** [kinglozzer/silverstripe-tinypng#5]
There is a bit of a gotcha / something unexpected with the .Compressed method.

If you have

    <% loop $SomeImages %>
        $Image.ScaleMaxWidth(1920).Compressed.URL
        ....
        $Image.ScaleMaxWidth(40).URL
    <% end_loop %>

Then the src/ImageExtension.php -> getFormattedImage -> `if ($this->getCompressed()) {` method will be true in both instances.

So even thou we have $Image.ScaleMaxWidth(40).URL then it will compress it anyway since Compressed sets a class variable which is not cleared on the next run.

**Comment by nfauchelle** [comment]
Noticed, that 
```
    $Image.ScaleMaxWidth(1920).Compressed.URL
    $Image.ScaleMaxWidth(40).URL
```
calls that function twice, and 

```
    $Image.ScaleMaxWidth(1920).Compressed.URL
    $Image.ScaleMaxWidth(40).Compressed.URL
```
will call it three times.

Maybe the best way to fix this, is change the `protected $compressed = false;` to a `$requiresCompression` variable instead. Then change `if ($this->getCompressed()) {` to `if ($this->requiresCompression()) {` and then once it's compressed it flicks the class variable back to false.

**Comment by lozcalver** [comment]
Nice find! I think we could solve this without renaming or altering the method, just by adding a `$this->compressed = false` inside the `if ($this->getCompressed())` statement.

This is probably a good sign that the approach I took was the wrong one 😉. It’d be better to handle compression in the “backend” on write

**Comment by nfauchelle** [comment]
The reason I would change the variable is because it implies that the image is compressed / not compressed. Where as your using it more as a check to see if you need to compress the image.

We considered using the compression part and extract it out to an extension which hooked into afterUpload, but found when something like ScaleMaxWidth was called, the image size would ballon again - so this compressed call really would need to be the last thing done before write to disk (similar to now, but without overriding that method it does).

**Comment by lozcalver** [comment]
> The reason I would change the variable is because it implies that the image is compressed / not compressed. Where as your using it more as a check to see if you need to compress the image.

Good point, I’ll just change it and bump the version number.

> We considered using the compression part and extract it out to an extension which hooked into afterUpload, but found when something like ScaleMaxWidth was called, the image size would ballon again - so this compressed call really would need to be the last thing done before write to disk 

Yeah that was the main problem I had - which is also the reason why you have to call `.Compressed` last 😞

**Comment by lozcalver** [comment]
Made that change in https://github.com/kinglozzer/silverstripe-tinypng/commit/47beaf4f6b8554283d0799b0a62750af11f83df9 and tagged as `1.0.0`
