### ISSUE TITLE
After installing module .CMSThumbnail doesn't work in $summary_fields

### ISSUE THREAD

**Issue by Codesesh** [kinglozzer/silverstripe-tinypng#6]
After installing this module all of our $summary_fields that use the .CMSThumbnail method appear blank. 

E.g 

Image.CMSThumbnail

Really strange issue, couldn't work out why it was doing this.. We are using silverstripe CMS & framework 3.5.3

**Comment by lozcalver** [comment]
Ah, I can see the problem - the `Image` API has changed slightly since I built this

**Comment by lozcalver** [comment]
I’ve pushed a new tag `2.0.0` to resolve this
