### ISSUE TITLE
Image table doesn't exits anymore

### ISSUE THREAD

**Issue by beshad** [kinglozzer/silverstripe-tinypng#8]
Hi there, great work but I am having an issue with re-building my Database after installing this module. if the DB already exists everything works fine but if you delete the DB and then recreate it via dev/build, the Image table does not get recreated and therefore can't upload any images as you would normally do. dev/build created the 'Image' table after removal of the module. any idea?  is this a bug in the repo or something else i am missing? cheers

**Comment by lozcalver** [comment]
Hmm, `Image` doesn’t get a table by default, are you using another module which adds some database fields to `Image`?

**Comment by beshad** [comment]
yes i actually dp. here is composer.json 
![screen shot 2017-11-24 at 10 17 46 pm](https://user-images.githubusercontent.com/14914745/33203579-62dd4d0c-d165-11e7-8171-1d82b1bc9ec7.png)

thanks

**Comment by lozcalver** [comment]
I’ve just pushed a new tag `2.0.1` which should solve this :)

**Comment by beshad** [comment]
Awesome. I can confirm that your fixed the issue I had. Thanks
