### ISSUE TITLE
SS4 Release?

### ISSUE THREAD

**Issue by bummzack** [kinglozzer/silverstripe-tinypng#9]
Any plans on releasing this for SS4?

**Comment by lozcalver** [comment]
Good question! I don’t see any reason why not, it should be possible to ditch some of the hacks like `class TinyPngImage extends Image` with the new asset system too.

I think the approach I’d investigate first is writing an encoder for `intervention/image` which can pass images over to tinypng. Hopefully that’s possible, and hopefully it’s easy to configure SilverStripe to use that driver!

**Comment by martinviolet88** [comment]
Hi, any updates on releasing the 4.0 version?:)
